version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: baycap_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: baycap_db
      MONGO_INITDB_ROOT_USERNAME: wildclown
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: